//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    
    public partial class CurrencyPairsWithIso
    {
        public int saleCurrency { get; set; }
        public int buyCurrency { get; set; }
        public string isoSale { get; set; }
        public string isoBuy { get; set; }
    }
}
