//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entities
{
    using System;
    
    public partial class Currency
    {
        public int currencyID { get; set; }
        public string name { get; set; }
        public string symbol { get; set; }
        public string iso { get; set; }
    }
}
